// Compile public/login.html into src/consoleHtml.mjs.
//
// Why: the Cloudflare Worker bundle can't read files, and relying on the
// [assets] binding behaved inconsistently locally. Embedding the shell as a JS
// string makes both deployments serve byte-identical HTML.
//
// Run this after every edit to public/login.html:  npm run build:html
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const html = fs.readFileSync(path.join(root, 'public', 'login.html'), 'utf8');
const out =
  '// AUTO-GENERATED by `npm run build:html` from public/login.html — do NOT edit.\n' +
  '// The login shell is embedded as a string so the Worker bundle needs neither\n' +
  '// the filesystem nor an [assets] binding.\n' +
  'export const LOGIN_HTML = ' + JSON.stringify(html) + ';\n';

fs.writeFileSync(path.join(root, 'src', 'consoleHtml.mjs'), out);
console.log(`build:html  public/login.html (${html.length}B) -> src/consoleHtml.mjs (${out.length}B)`);
